### ISSUE TITLE
one job execute twice or Three times

### ISSUE THREAD

**Issue by xiaowj** [jarekwg/django-apscheduler#12] opened 2018-01-28 07:15 UTC
in my project,i use django 2.0.1 and django-apscheduler (0.2.3),i register one job by interval,but in certain time it execute more once,also use apscheduler without  django-apscheduler,it work very well

**Comment by xiaowj** [comment] 2018-01-28 07:41
i add multi job,not one,ths result is job confusion

**Comment by sallyruthstruik** [comment] 2018-01-28 09:05
Could you please provide code snippet?

**Comment by xiaowj** [comment] 2018-01-28 14:51
yes sure
```python
tbs = BackgroundScheduler()
tbs.add_jobstore(DjangoJobStore())


@register_job(tbs, 'interval', minutes=0, seconds=10, id='tbs')
def task():
    logger.info('task')


bs = BackgroundScheduler()
bs.add_jobstore(DjangoJobStore())


@register_job(bs, 'interval', minutes=0, seconds=11, id='bs')
def task():
    logger.info('task2')


register_events(tbs)
tbs.start()

register_events(bs)
bs.start()
```

**Comment by sallyruthstruik** [comment] 2018-01-29 09:28
@xiaowj Looks like problem in register_events call. You can remove it while I'm searching for a solution...

**Comment by xiaowj** [comment] 2018-01-29 09:49
@sallyruthstruik ok,i will update when you fix it

**Comment by sallyruthstruik** [comment] 2018-01-29 10:12
Gothcha. When you create two schedulers, each of them recognizes each task separately. 

You can reproduce this behavior with pure apscheduler:
```python
import datetime

from apscheduler.schedulers.background import BackgroundScheduler
sch1 = BackgroundScheduler()
sch2 = BackgroundScheduler()

def test():
    print(datetime.datetime.now(), "TEST")

sch1.add_job(test, "interval", seconds=10, id="test")
sch2.add_job(test, "interval", seconds=10, id="test2")
sch1.start()
sch2.start()
import logging
logging.basicConfig(level="INFO")
```

And I got:
```
INFO:apscheduler.executors.default:Running job "test (trigger: interval[0:00:10], next run at: 2018-01-29 13:04:47 MSK)" (scheduled at 2018-01-29 13:04:47.750244+03:00)
2018-01-29 13:04:47.776702 TEST
INFO:apscheduler.executors.default:Running job "test (trigger: interval[0:00:10], next run at: 2018-01-29 13:04:57 MSK)" (scheduled at 2018-01-29 13:04:47.750474+03:00)
INFO:apscheduler.executors.default:Job "test (trigger: interval[0:00:10], next run at: 2018-01-29 13:04:57 MSK)" executed successfully
INFO:apscheduler.executors.default:Job "test (trigger: interval[0:00:10], next run at: 2018-01-29 13:04:57 MSK)" executed successfully
2018-01-29 13:04:47.782127 TEST
```

To summarize, I think it is not a bug. You don't need several instances of scheduler (If you need, please describe your case with more details). Use one scheduler and configure as much executors as you need like in example here: https://apscheduler.readthedocs.io/en/latest/userguide.html#configuring-the-scheduler

**Comment by sallyruthstruik** [comment] 2018-02-01 10:02
@xiaowj I'm closing the issue. If you have any other questions fill free to contact me via email(staskaledin@gmail.com) or telegram (sallyruthstruik)

**Closed by sallyruthstruik** 2018-02-01 10:02 UTC

**Comment by taowenleon** [comment] 2018-04-21 08:32
@xiaowj Have you solved this problem yet? I met the same problem with you when using apscheduler to write data to oracle.

**Comment by dreamjole** [comment] 2018-07-25 03:45
@taowenleon how can you migrate on oracle，the default table name django_apschedular_djangojobexecution exceed 30 charachters of oracle table name

**Comment by jonamadk** [comment] 2021-06-08 14:14
@sallyruthstruik I am new to this any suggestion for it's implementation in Django would be appreciable , Once the job executes it restarts the server and then executes again. For details about my query https://stackoverflow.com/questions/67888786/apscheduler-job-in-django-executes-twice

**Comment by jcass77** [comment] 2021-06-08 14:25
@jonamadk, the README contains full details on the recommended approach: (1) don't use a `BackgroundScheduler` and (2) don't have more than one scheduler running concurrently.
