### ISSUE TITLE
When there is only one task and it is paused, my project raise 'DjangoJob matching query does not exist.'

### ISSUE THREAD

**Issue by angeic** [jarekwg/django-apscheduler#25] opened 2018-06-12 03:37 UTC
When there is only one task and it is paused, my project raise 'DjangoJob matching query does not exist.'
May be the problem is here:
Now the next_run_time for all jobs is Null, there are several places where next_run_time are needed.

**Comment by sallyruthstruik** [comment] 2018-07-10 14:10
Duplicate of https://github.com/jarekwg/django-apscheduler/issues/26

**Closed by sallyruthstruik** 2018-07-10 14:10 UTC
